--- 
components: 
  schemas: 

    # This is a base definition of a Destination Quiz Race
    Race: 
      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.DestinationQuiz/master/Race/model.yaml#/Race"

    # This is a base definition of a Destination Quiz Question
    Question: 
      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.DestinationQuiz/master/Question/model.yaml#/Question"

info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object