---
# Copyright (c) 2022 Contributors to Smart Destination Models initiative
# 


components:
  schemas: 
    Race: 
      $ref: "https://raw.githubusercontent.com/dpatil-fw/dataModel.DestinationQuiz/master/Race/model.yaml#/Race"
info:
  description:  |
    This entity contains a harmonised description of a Race
  title: Race
  version: "1.0.0"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Race
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://github.com/dpatil-fw/dataModel.DestinationQuiz/master/Race/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://github.com/dpatil-fw/dataModel.DestinationQuiz/master/Race/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
